### PR TITLE
Add type highlighting

### PR DESCRIPTION
**Pull request by seripap**
Adds type highlighting. To be completely honest, I don't even know what i'm doing 🤷‍♀️ , but the attached is the end goal.

Screen Shot 2020-09-19 at 2 33 45 PM

### CODE REVIEW

**Comment by tooolbox** [comment]
Ideally `User` and `struct` would have different colors, and `main` would not be colored like a type.  Also, `package` and `import` are generally colored one way, while `type` and `func` are different (even though they're all [keywords](https://golang.org/ref/spec#Keywords) per the spec).

Here's what I see in Sublime, with the default Monokai theme:

Screen Shot 2020-09-19 at 1 47 30 PM

Note that only the builtin types are highlighted, the plugins I've used for Go never highlight custom types.

**Comment by seripap** [comment]
Here's where we are currently. Not 100% following specs in order to color them differently.

Screen Shot 2020-09-21 at 9 34 22 AM

**Comment by GwynethLlewelyn** [comment]
Oh wow, you're a guru! For someone claiming that you don't know what you're doing, I'm _really_ impressed with your changes. They make a lot of sense to me, at least... and I agree, they're a step towards the goal. I believe that the problem with **Go** is that it has an awkward (but simple!) syntax, and, because it shares many elements with C-style languages, but adds a lot of its own, the parsers get confused...

Anyway, I just have a question, at some point in your cod you have a `<ends-with>x`. What's the `x` for?

**Comment by seripap** [comment]
> Oh wow, you're a guru! For someone claiming that you don't know what you're doing, I'm _really_ impressed with your changes. They make a lot of sense to me, at least... and I agree, they're a step towards the goal. I believe that the problem with **Go** is that it has an awkward (but simple!) syntax, and, because it shares many elements with C-style languages, but adds a lot of its own, the parsers get confused...
> 
> Anyway, I just have a question, at some point in your code you have a `<ends-with>x`. What's the `x` for?
> 
> Also, _right now_, my poor MacBook Pro is trying very hard to tackle a badly gone upgrade, an operation which takes hours nd hours, which means that until it decides to boot again, I'm stumped -- I can merge your request, but I cannot upload the revised file to Panic's repository...

Ah the `x` is a typo, i'll fix in the next push up. I'm not sure if the PR is ready for merge yet, I think it needs a few more tweaks and i'll test it on a large scale project to make sure the highlighting makes sense.

**Comment by GwynethLlewelyn** [comment]
All right! Thanks :-) Let me know when you think it's ready to go. I'm really not an expert on these things; 99.9% of all my projects on GitHub are 'lone projects' with little interest (I just want to make sure I don't lose them _again_), so I hope I'm not violating GitHub etiquette... 😅

**Comment by tooolbox** [comment]
Getting better 👍   

May I recommend that [operators](https://golang.org/ref/spec#Operators) have their own scope/color?

```go
||
&&
==
!=
<
<=
>
>=
+
-
|
^
*
/
%
<<
>>
&
&^
!
<-
...
:=
=
```

(This list is actually more than just operators, but it's what plugins typically highlight.)

Note that this list does *not* include:

```go
:
.
_
```

Also, if you can highlight formatting specifiers such as `%s`, `%v`, `%+v`, `%w`, `%#v`, `%9.2f`, `% X` (yes with a space) and so on, as they occur within strings, that would be great.  The specifications and a mostly complete list are [in the `fmt` package docs](https://golang.org/pkg/fmt/#hdr-Printing).

> I believe that the problem with Go is that it has an awkward (but simple!) syntax, and, because it shares many elements with C-style languages, but adds a lot of its own, the parsers get confused...

I don't believe this is accurate, Go's syntax is famously straightforward, specifically so that it can be parsed easily 😄 

> I hope I'm not violating GitHub etiquette... 😅

You're doing great, no worries.

**Comment by tooolbox** [comment]
@seripap if you're satisfied with where you're at and want to merge it, it can always be improved later.  You're obviously doing free work; don't take my comments as some harsh criticism 😉

**Comment by seripap** [comment]
Sure, i'll convert over to get merged in and make some more enhancements later on.

**Comment by GwynethLlewelyn** [comment]
Thanks!!

**Comment by GwynethLlewelyn** [comment]
Actually, I'm revising the `README.md` to add you guys some credit, as well as changing the code to use `gopls` on the path (as opposed to the cludgy way it's being done now, I agree it's not the best way) i.e. fixing #2 as well, and then I think I can release a new version... stay tuned lol

**Comment by GwynethLlewelyn** [comment]
@all-contributors please add @seripap for code; add @tooolbox for ideas and question

**Comment by GwynethLlewelyn** [comment]
@all-contributors please add @seripap for code

**Comment by GwynethLlewelyn** [comment]
@all-contributors add @tooolbox for ideas and question

**Pull request merged**
